server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://192.91.87.105:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: peiqi666
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
# MinIO对象存储相关配置
minio:
  endpoint: http://192.91.87.105:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: admin #访问的key
  secretKey: peiqi666 #访问的秘钥

